//**************************************************************************
//**
//**	See jlquake.txt for copyright info.
//**
//**	This program is free software; you can redistribute it and/or
//**  modify it under the terms of the GNU General Public License
//**  as published by the Free Software Foundation; either version 3
//**  of the License, or (at your option) any later version.
//**
//**	This program is distributed in the hope that it will be useful,
//**  but WITHOUT ANY WARRANTY; without even the implied warranty of
//**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//**  included (gnu.txt) GNU General Public License for more details.
//**
//**************************************************************************

#ifndef GLF_V1_X
#define DID_DEFINE_X_MACROS
#define GLF_V1_X(n, t1, p1)			GLF_V1(n, t1, p1)
#define GLF_V2_X(n, t1, p1, t2, p2)	GLF_V2(n, t1, p1, t2, p2)
#define GLF_V3_X(n, t1, p1, t2, p2, t3, p3)	GLF_V3(n, t1, p1, t2, p2, t3, p3)
#define GLF_V4_X(n, t1, p1, t2, p2, t3, p3, t4, p4)	GLF_V4(n, t1, p1, t2, p2, t3, p3, t4, p4)
#endif

GLF_V2(Accum, GLenum, op, GLfloat, value)
GLF_V2_X(AlphaFunc, GLenum, func, GLclampf, ref)
GLF_3(GLboolean, AreTexturesResident, GLsizei, n, const GLuint*, textures, GLboolean*, residences)
GLF_V1(ArrayElement, GLint, i)
GLF_V1_X(Begin, GLenum, mode)
GLF_V2_X(BindTexture, GLenum, target, GLuint, texture)
GLF_V7(Bitmap, GLsizei, width, GLsizei, height, GLfloat, xorig, GLfloat, yorig, GLfloat, xmove, GLfloat, ymove, const GLubyte*, bitmap)
GLF_V2_X(BlendFunc, GLenum, sfactor, GLenum, dfactor)
GLF_V1_X(CallList, GLuint, list)
GLF_V3(CallLists, GLsizei, n, GLenum, type, const GLvoid*, lists)
GLF_V1_X(Clear, GLbitfield, mask)
GLF_V4(ClearAccum, GLfloat, red, GLfloat, green, GLfloat, blue, GLfloat, alpha)
GLF_V4(ClearColor, GLclampf, red, GLclampf, green, GLclampf, blue, GLclampf, alpha)
GLF_V1_X(ClearDepth, GLclampd, depth)
GLF_V1(ClearIndex, GLfloat, c)
GLF_V1_X(ClearStencil, GLint, s)
GLF_V2(ClipPlane, GLenum, plane, const GLdouble*, equation)
GLF_V3(Color3b, GLbyte, red, GLbyte, green, GLbyte, blue)
GLF_V1(Color3bv, const GLbyte*, v)
GLF_V3(Color3d, GLdouble, red, GLdouble, green, GLdouble, blue)
GLF_V1(Color3dv, const GLdouble*, v)
GLF_V3(Color3f, GLfloat, red, GLfloat, green, GLfloat, blue)
GLF_V1(Color3fv, const GLfloat*, v)
GLF_V3(Color3i, GLint, red, GLint, green, GLint, blue)
GLF_V1(Color3iv, const GLint*, v)
GLF_V3(Color3s, GLshort, red, GLshort, green, GLshort, blue)
GLF_V1(Color3sv, const GLshort*, v)
GLF_V3(Color3ub, GLubyte, red, GLubyte, green, GLubyte, blue)
GLF_V1(Color3ubv, const GLubyte*, v)
GLF_V3(Color3ui, GLuint, red, GLuint, green, GLuint, blue)
GLF_V1(Color3uiv, const GLuint*, v)
GLF_V3(Color3us, GLushort, red, GLushort, green, GLushort, blue)
GLF_V1(Color3usv, const GLushort*, v)
GLF_V4(Color4b, GLbyte, red, GLbyte, green, GLbyte, blue, GLbyte, alpha)
GLF_V1(Color4bv, const GLbyte*, v)
GLF_V4(Color4d, GLdouble, red, GLdouble, green, GLdouble, blue, GLdouble, alpha)
GLF_V1(Color4dv, const GLdouble*, v)
GLF_V4_X(Color4f, GLfloat, red, GLfloat, green, GLfloat, blue, GLfloat, alpha)
GLF_V1_X(Color4fv, const GLfloat*, v)
GLF_V4(Color4i, GLint, red, GLint, green, GLint, blue, GLint, alpha)
GLF_V1(Color4iv, const GLint*, v)
GLF_V4(Color4s, GLshort, red, GLshort, green, GLshort, blue, GLshort, alpha)
GLF_V1(Color4sv, const GLshort*, v)
GLF_V4(Color4ub, GLubyte, red, GLubyte, green, GLubyte, blue, GLubyte, alpha)
GLF_V1(Color4ubv, const GLubyte*, v)
GLF_V4(Color4ui, GLuint, red, GLuint, green, GLuint, blue, GLuint, alpha)
GLF_V1(Color4uiv, const GLuint*, v)
GLF_V4(Color4us, GLushort, red, GLushort, green, GLushort, blue, GLushort, alpha)
GLF_V1(Color4usv, const GLushort*, v)
GLF_V4(ColorMask, GLboolean, red, GLboolean, green, GLboolean, blue, GLboolean, alpha)
GLF_V2(ColorMaterial, GLenum, face, GLenum, mode)
GLF_V4_X(ColorPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid*, pointer)
GLF_V5(CopyPixels, GLint, x, GLint, y, GLsizei, width, GLsizei, height, GLenum, type)
GLF_V7(CopyTexImage1D, GLenum, target, GLint, level, GLenum, internalFormat, GLint, x, GLint, y, GLsizei, width, GLint, border)
GLF_V8(CopyTexImage2D, GLenum, target, GLint, level, GLenum, internalFormat, GLint, x, GLint, y, GLsizei, width, GLsizei, height, GLint, border)
GLF_V6(CopyTexSubImage1D, GLenum, target, GLint, level, GLint, xoffset, GLint, x, GLint, y, GLsizei, width)
GLF_V8(CopyTexSubImage2D, GLenum, target, GLint, level, GLint, xoffset, GLint, yoffset, GLint, x, GLint, y, GLsizei, width, GLsizei, height)
GLF_V1_X(CullFace, GLenum, mode)
GLF_V2(DeleteLists, GLuint, list, GLsizei, range)
GLF_V2(DeleteTextures, GLsizei, n, const GLuint*, textures)
GLF_V1_X(DepthFunc, GLenum, func)
GLF_V1_X(DepthMask, GLboolean, flag)
GLF_V2_X(DepthRange, GLclampd, zNear, GLclampd,zFar)
GLF_V1_X(Disable, GLenum, cap)
GLF_V1_X(DisableClientState, GLenum, array)
GLF_V3(DrawArrays, GLenum, mode, GLint, first, GLsizei, count)
GLF_V1(DrawBuffer, GLenum, mode)
GLF_V4_X(DrawElements, GLenum, mode, GLsizei, count, GLenum, type, const GLvoid*, indices)
GLF_V5(DrawPixels, GLsizei, width, GLsizei, height, GLenum, format, GLenum, type, const GLvoid*, pixels)
GLF_V1(EdgeFlag, GLboolean, flag)
GLF_V2(EdgeFlagPointer, GLsizei, stride, const GLvoid*, pointer)
GLF_V1(EdgeFlagv, const GLboolean*, flag)
GLF_V1_X(Enable, GLenum, cap)
GLF_V1_X(EnableClientState, GLenum, array)
GLF_V0(End)
GLF_V0(EndList)
GLF_V1(EvalCoord1d, GLdouble, u)
GLF_V1(EvalCoord1dv, const GLdouble*, u)
GLF_V1(EvalCoord1f, GLfloat, u)
GLF_V1(EvalCoord1fv, const GLfloat*, u)
GLF_V2(EvalCoord2d, GLdouble, u, GLdouble, v)
GLF_V1(EvalCoord2dv, const GLdouble*, u)
GLF_V2(EvalCoord2f, GLfloat, u, GLfloat, v)
GLF_V1(EvalCoord2fv, const GLfloat*, u)
GLF_V3(EvalMesh1, GLenum, mode, GLint, i1, GLint, i2)
GLF_V5(EvalMesh2, GLenum, mode, GLint, i1, GLint, i2, GLint, j1, GLint, j2)
GLF_V1(EvalPoint1, GLint, i)
GLF_V2(EvalPoint2, GLint, i, GLint, j)
GLF_V3(FeedbackBuffer, GLsizei, size, GLenum, type, GLfloat*, buffer)
GLF_V0(Finish)
GLF_V0(Flush)
GLF_V2(Fogf, GLenum, pname, GLfloat, param)
GLF_V2(Fogfv, GLenum, pname, const GLfloat*, params)
GLF_V2(Fogi, GLenum, pname, GLint, param)
GLF_V2(Fogiv, GLenum, pname, const GLint*, params)
GLF_V1(FrontFace, GLenum, mode)
GLF_V6(Frustum, GLdouble, left, GLdouble, right, GLdouble, bottom, GLdouble, top, GLdouble, zNear, GLdouble, zFar)
GLF_1(GLuint, GenLists, GLsizei, range)
GLF_V2(GenTextures, GLsizei, n, GLuint*, textures)
GLF_V2(GetBooleanv, GLenum, pname, GLboolean*, params)
GLF_V2(GetClipPlane, GLenum, plane, GLdouble*, equation)
GLF_V2(GetDoublev, GLenum, pname, GLdouble*, params)
GLF_0(GLenum, GetError)
GLF_V2(GetFloatv, GLenum, pname, GLfloat*, params)
GLF_V2(GetIntegerv, GLenum, pname, GLint*, params)
GLF_V3(GetLightfv, GLenum, light, GLenum, pname, GLfloat*, params)
GLF_V3(GetLightiv, GLenum, light, GLenum, pname, GLint*, params)
GLF_V3(GetMapdv, GLenum, target, GLenum, query, GLdouble*, v)
GLF_V3(GetMapfv, GLenum, target, GLenum, query, GLfloat*, v)
GLF_V3(GetMapiv, GLenum, target, GLenum, query, GLint*, v)
GLF_V3(GetMaterialfv, GLenum, face, GLenum, pname, GLfloat*, params)
GLF_V3(GetMaterialiv, GLenum, face, GLenum, pname, GLint*, params)
GLF_V2(GetPixelMapfv, GLenum, map, GLfloat*, values)
GLF_V2(GetPixelMapuiv, GLenum, map, GLuint*, values)
GLF_V2(GetPixelMapusv, GLenum, map, GLushort*, values)
GLF_V2(GetPointerv, GLenum, pname, GLvoid**, params)
GLF_V1(GetPolygonStipple, GLubyte*, mask)
GLF_1(const GLubyte*, GetString, GLenum, name)
GLF_V3(GetTexEnvfv, GLenum, target, GLenum, pname, GLfloat*, params)
GLF_V3(GetTexEnviv, GLenum, target, GLenum, pname, GLint*, params)
GLF_V3(GetTexGendv, GLenum, coord, GLenum, pname, GLdouble*, params)
GLF_V3(GetTexGenfv, GLenum, coord, GLenum, pname, GLfloat*, params)
GLF_V3(GetTexGeniv, GLenum, coord, GLenum, pname, GLint*, params)
GLF_V5(GetTexImage, GLenum, target, GLint, level, GLenum, format, GLenum, type, GLvoid*, pixels)
GLF_V4(GetTexLevelParameterfv, GLenum, target, GLint, level, GLenum, pname, GLfloat*, params)
GLF_V4(GetTexLevelParameteriv, GLenum, target, GLint, level, GLenum, pname, GLint*, params)
GLF_V3(GetTexParameterfv, GLenum, target, GLenum, pname, GLfloat*, params)
GLF_V3(GetTexParameteriv, GLenum, target, GLenum, pname, GLint*, params)
GLF_V2_X(Hint, GLenum, target, GLenum, mode)
GLF_V1(IndexMask, GLuint, mask)
GLF_V3(IndexPointer, GLenum, type, GLsizei, stride, const GLvoid*, pointer)
GLF_V1(Indexd, GLdouble, c)
GLF_V1(Indexdv, const GLdouble*, c)
GLF_V1(Indexf, GLfloat, c)
GLF_V1(Indexfv, const GLfloat*, c)
GLF_V1(Indexi, GLint, c)
GLF_V1(Indexiv, const GLint*, c)
GLF_V1(Indexs, GLshort, c)
GLF_V1(Indexsv, const GLshort*, c)
GLF_V1(Indexub, GLubyte, c)
GLF_V1(Indexubv, const GLubyte*, c)
GLF_V0(InitNames)
GLF_V3(InterleavedArrays, GLenum, format, GLsizei, stride, const GLvoid*, pointer)
GLF_1(GLboolean, IsEnabled, GLenum, cap)
GLF_1(GLboolean, IsList, GLuint, list)
GLF_1(GLboolean, IsTexture, GLuint, texture)
GLF_V2(LightModelf, GLenum, pname, GLfloat, param)
GLF_V2(LightModelfv, GLenum, pname, const GLfloat*, params)
GLF_V2(LightModeli, GLenum, pname, GLint, param)
GLF_V2(LightModeliv, GLenum, pname, const GLint*, params)
GLF_V3(Lightf, GLenum, light, GLenum, pname, GLfloat, param)
GLF_V3(Lightfv, GLenum, light, GLenum, pname, const GLfloat*, params)
GLF_V3(Lighti, GLenum, light, GLenum, pname, GLint, param)
GLF_V3(Lightiv, GLenum, light, GLenum, pname, const GLint*, params)
GLF_V2(LineStipple, GLint, factor, GLushort, pattern)
GLF_V1(LineWidth, GLfloat, width)
GLF_V1(ListBase, GLuint, base)
GLF_V0(LoadIdentity)
GLF_V1(LoadMatrixd, const GLdouble*, m)
GLF_V1(LoadMatrixf, const GLfloat*, m)
GLF_V1(LoadName, GLuint, name)
GLF_V1(LogicOp, GLenum, opcode)
GLF_V6(Map1d, GLenum, target, GLdouble, u1, GLdouble, u2, GLint, stride, GLint, order, const GLdouble*, points)
GLF_V6(Map1f, GLenum, target, GLfloat, u1, GLfloat, u2, GLint, stride, GLint, order, const GLfloat*, points)
GLF_V10(Map2d, GLenum, target, GLdouble, u1, GLdouble, u2, GLint, ustride, GLint, uorder, GLdouble, v1, GLdouble, v2, GLint, vstride, GLint, vorder, const GLdouble*, points)
GLF_V10(Map2f, GLenum, target, GLfloat, u1, GLfloat, u2, GLint, ustride, GLint, uorder, GLfloat, v1, GLfloat, v2, GLint, vstride, GLint, vorder, const GLfloat*, points)
GLF_V3(MapGrid1d, GLint, un, GLdouble, u1, GLdouble, u2)
GLF_V3(MapGrid1f, GLint, un, GLfloat, u1, GLfloat, u2)
GLF_V6(MapGrid2d, GLint, un, GLdouble, u1, GLdouble, u2, GLint, vn, GLdouble, v1, GLdouble, v2)
GLF_V6(MapGrid2f, GLint, un, GLfloat, u1, GLfloat, u2, GLint, vn, GLfloat, v1, GLfloat, v2)
GLF_V3(Materialf, GLenum, face, GLenum, pname, GLfloat, param)
GLF_V3(Materialfv, GLenum, face, GLenum, pname, const GLfloat*, params)
GLF_V3(Materiali, GLenum, face, GLenum, pname, GLint, param)
GLF_V3(Materialiv, GLenum, face, GLenum, pname, const GLint*, params)
GLF_V1(MatrixMode, GLenum, mode)
GLF_V1(MultMatrixd, const GLdouble*, m)
GLF_V1(MultMatrixf, const GLfloat*, m)
GLF_V2(NewList, GLuint, list, GLenum, mode)
GLF_V3(Normal3b, GLbyte, nx, GLbyte, ny, GLbyte, nz)
GLF_V1(Normal3bv, const GLbyte*, v)
GLF_V3(Normal3d, GLdouble, nx, GLdouble, ny, GLdouble, nz)
GLF_V1(Normal3dv, const GLdouble*, v)
GLF_V3(Normal3f, GLfloat, nx, GLfloat, ny, GLfloat, nz)
GLF_V1(Normal3fv, const GLfloat*, v)
GLF_V3(Normal3i, GLint, nx, GLint, ny, GLint, nz)
GLF_V1(Normal3iv, const GLint*, v)
GLF_V3(Normal3s, GLshort, nx, GLshort, ny, GLshort, nz)
GLF_V1(Normal3sv, const GLshort*, v)
GLF_V3(NormalPointer, GLenum, type, GLsizei, stride, const GLvoid*, pointer)
GLF_V6(Ortho, GLdouble, left, GLdouble, right, GLdouble, bottom, GLdouble, top, GLdouble, zNear, GLdouble, zFar)
GLF_V1(PassThrough, GLfloat, token)
GLF_V3(PixelMapfv, GLenum, map, GLsizei, mapsize, const GLfloat*, values)
GLF_V3(PixelMapuiv, GLenum, map, GLsizei, mapsize, const GLuint*, values)
GLF_V3(PixelMapusv, GLenum, map, GLsizei, mapsize, const GLushort*, values)
GLF_V2(PixelStoref, GLenum, pname, GLfloat, param)
GLF_V2(PixelStorei, GLenum, pname, GLint, param)
GLF_V2(PixelTransferf, GLenum, pname, GLfloat, param)
GLF_V2(PixelTransferi, GLenum, pname, GLint, param)
GLF_V2(PixelZoom, GLfloat, xfactor, GLfloat, yfactor)
GLF_V1(PointSize, GLfloat, size)
GLF_V2_X(PolygonMode, GLenum, face, GLenum, mode)
GLF_V2(PolygonOffset, GLfloat, factor, GLfloat, units)
GLF_V1(PolygonStipple, const GLubyte*, mask)
GLF_V0(PopAttrib)
GLF_V0(PopClientAttrib)
GLF_V0(PopMatrix)
GLF_V0(PopName)
GLF_V3(PrioritizeTextures, GLsizei, n, const GLuint*, textures, const GLclampf*, priorities)
GLF_V1(PushAttrib, GLbitfield, mask)
GLF_V1(PushClientAttrib, GLbitfield, mask)
GLF_V0(PushMatrix)
GLF_V1(PushName, GLuint, name)
GLF_V2(RasterPos2d, GLdouble, x, GLdouble, y)
GLF_V1(RasterPos2dv, const GLdouble*, v)
GLF_V2(RasterPos2f, GLfloat, x, GLfloat, y)
GLF_V1(RasterPos2fv, const GLfloat*, v)
GLF_V2(RasterPos2i, GLint, x, GLint, y)
GLF_V1(RasterPos2iv, const GLint*, v)
GLF_V2(RasterPos2s, GLshort, x, GLshort, y)
GLF_V1(RasterPos2sv, const GLshort*, v)
GLF_V3(RasterPos3d, GLdouble, x, GLdouble, y, GLdouble, z)
GLF_V1(RasterPos3dv, const GLdouble*, v)
GLF_V3(RasterPos3f, GLfloat, x, GLfloat, y, GLfloat, z)
GLF_V1(RasterPos3fv, const GLfloat*, v)
GLF_V3(RasterPos3i, GLint, x, GLint, y, GLint, z)
GLF_V1(RasterPos3iv, const GLint*, v)
GLF_V3(RasterPos3s, GLshort, x, GLshort, y, GLshort, z)
GLF_V1(RasterPos3sv, const GLshort*, v)
GLF_V4(RasterPos4d, GLdouble, x, GLdouble, y, GLdouble, z, GLdouble, w)
GLF_V1(RasterPos4dv, const GLdouble*, v)
GLF_V4(RasterPos4f, GLfloat, x, GLfloat, y, GLfloat, z, GLfloat, w)
GLF_V1(RasterPos4fv, const GLfloat*, v)
GLF_V4(RasterPos4i, GLint, x, GLint, y, GLint, z, GLint, w)
GLF_V1(RasterPos4iv, const GLint*, v)
GLF_V4(RasterPos4s, GLshort, x, GLshort, y, GLshort, z, GLshort, w)
GLF_V1(RasterPos4sv, const GLshort*, v)
GLF_V1(ReadBuffer, GLenum, mode)
GLF_V7(ReadPixels, GLint, x, GLint, y, GLsizei, width, GLsizei, height, GLenum, format, GLenum, type, GLvoid*, pixels)
GLF_V4(Rectd, GLdouble, x1, GLdouble, y1, GLdouble, x2, GLdouble, y2)
GLF_V2(Rectdv, const GLdouble*, v1, const GLdouble*, v2)
GLF_V4(Rectf, GLfloat, x1, GLfloat, y1, GLfloat, x2, GLfloat, y2)
GLF_V2(Rectfv, const GLfloat*, v1, const GLfloat*, v2)
GLF_V4(Recti, GLint, x1, GLint, y1, GLint, x2, GLint, y2)
GLF_V2(Rectiv, const GLint*, v1, const GLint*, v2)
GLF_V4(Rects, GLshort, x1, GLshort, y1, GLshort, x2, GLshort, y2)
GLF_V2(Rectsv, const GLshort*, v1, const GLshort*, v2)
GLF_1(GLint, RenderMode, GLenum, mode)
GLF_V4(Rotated, GLdouble, angle, GLdouble, x, GLdouble, y, GLdouble, z)
GLF_V4(Rotatef, GLfloat, angle, GLfloat, x, GLfloat, y, GLfloat, z)
GLF_V3(Scaled, GLdouble, x, GLdouble, y, GLdouble, z)
GLF_V3(Scalef, GLfloat, x, GLfloat, y, GLfloat, z)
GLF_V4_X(Scissor, GLint, x, GLint, y, GLsizei, width, GLsizei, height)
GLF_V2(SelectBuffer, GLsizei, size, GLuint*, buffer)
GLF_V1(ShadeModel, GLenum, mode)
GLF_V3(StencilFunc, GLenum, func, GLint, ref, GLuint, mask)
GLF_V1(StencilMask, GLuint, mask)
GLF_V3(StencilOp, GLenum, fail, GLenum, zfail, GLenum, zpass)
GLF_V1(TexCoord1d, GLdouble, s)
GLF_V1(TexCoord1dv, const GLdouble*, v)
GLF_V1(TexCoord1f, GLfloat, s)
GLF_V1(TexCoord1fv, const GLfloat*, v)
GLF_V1(TexCoord1i, GLint, s)
GLF_V1(TexCoord1iv, const GLint*, v)
GLF_V1(TexCoord1s, GLshort, s)
GLF_V1(TexCoord1sv, const GLshort*, v)
GLF_V2(TexCoord2d, GLdouble, s, GLdouble, t)
GLF_V1(TexCoord2dv, const GLdouble*, v)
GLF_V2(TexCoord2f, GLfloat, s, GLfloat, t)
GLF_V1(TexCoord2fv, const GLfloat*, v)
GLF_V2(TexCoord2i, GLint, s, GLint, t)
GLF_V1(TexCoord2iv, const GLint*, v)
GLF_V2(TexCoord2s, GLshort, s, GLshort, t)
GLF_V1(TexCoord2sv, const GLshort*, v)
GLF_V3(TexCoord3d, GLdouble, s, GLdouble, t, GLdouble, r)
GLF_V1(TexCoord3dv, const GLdouble*, v)
GLF_V3(TexCoord3f, GLfloat, s, GLfloat, t, GLfloat, r)
GLF_V1(TexCoord3fv, const GLfloat*, v)
GLF_V3(TexCoord3i, GLint, s, GLint, t, GLint, r)
GLF_V1(TexCoord3iv, const GLint*, v)
GLF_V3(TexCoord3s, GLshort, s, GLshort, t, GLshort, r)
GLF_V1(TexCoord3sv, const GLshort*, v)
GLF_V4(TexCoord4d, GLdouble, s, GLdouble, t, GLdouble, r, GLdouble, q)
GLF_V1(TexCoord4dv, const GLdouble*, v)
GLF_V4(TexCoord4f, GLfloat, s, GLfloat, t, GLfloat, r, GLfloat, q)
GLF_V1(TexCoord4fv, const GLfloat*, v)
GLF_V4(TexCoord4i, GLint, s, GLint, t, GLint, r, GLint, q)
GLF_V1(TexCoord4iv, const GLint*, v)
GLF_V4(TexCoord4s, GLshort, s, GLshort, t, GLshort, r, GLshort, q)
GLF_V1(TexCoord4sv, const GLshort*, v)
GLF_V4_X(TexCoordPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid*, pointer)
GLF_V3_X(TexEnvf, GLenum, target, GLenum, pname, GLfloat, param)
GLF_V3(TexEnvfv, GLenum, target, GLenum, pname, const GLfloat*, params)
GLF_V3_X(TexEnvi, GLenum, target, GLenum, pname, GLint, param)
GLF_V3(TexEnviv, GLenum, target, GLenum, pname, const GLint*, params)
GLF_V3(TexGend, GLenum, coord, GLenum, pname, GLdouble, param)
GLF_V3(TexGendv, GLenum, coord, GLenum, pname, const GLdouble*, params)
GLF_V3(TexGenf, GLenum, coord, GLenum, pname, GLfloat, param)
GLF_V3(TexGenfv, GLenum, coord, GLenum, pname, const GLfloat*, params)
GLF_V3(TexGeni, GLenum, coord, GLenum, pname, GLint, param)
GLF_V3(TexGeniv, GLenum, coord, GLenum, pname, const GLint*, params)
GLF_V8(TexImage1D, GLenum, target, GLint, level, GLint, internalformat, GLsizei, width, GLint, border, GLenum, format, GLenum, type, const GLvoid*, pixels)
GLF_V9(TexImage2D, GLenum, target, GLint, level, GLint, internalformat, GLsizei, width, GLsizei, height, GLint, border, GLenum, format, GLenum, type, const GLvoid*, pixels)
GLF_V3_X(TexParameterf, GLenum, target, GLenum, pname, GLfloat, param)
GLF_V3(TexParameterfv, GLenum, target, GLenum, pname, const GLfloat*, params)
GLF_V3_X(TexParameteri, GLenum, target, GLenum, pname, GLint, param)
GLF_V3(TexParameteriv, GLenum, target, GLenum, pname, const GLint*, params)
GLF_V7(TexSubImage1D, GLenum, target, GLint, level, GLint, xoffset, GLsizei, width, GLenum, format, GLenum, type, const GLvoid*, pixels)
GLF_V9(TexSubImage2D, GLenum, target, GLint, level, GLint, xoffset, GLint, yoffset, GLsizei, width, GLsizei, height, GLenum, format, GLenum, type, const GLvoid*, pixels)
GLF_V3(Translated, GLdouble, x, GLdouble, y, GLdouble, z)
GLF_V3(Translatef, GLfloat, x, GLfloat, y, GLfloat, z)
GLF_V2(Vertex2d, GLdouble, x, GLdouble, y)
GLF_V1(Vertex2dv, const GLdouble*, v)
GLF_V2(Vertex2f, GLfloat, x, GLfloat, y)
GLF_V1(Vertex2fv, const GLfloat*, v)
GLF_V2(Vertex2i, GLint, x, GLint, y)
GLF_V1(Vertex2iv, const GLint*, v)
GLF_V2(Vertex2s, GLshort, x, GLshort, y)
GLF_V1(Vertex2sv, const GLshort*, v)
GLF_V3(Vertex3d, GLdouble, x, GLdouble, y, GLdouble, z)
GLF_V1(Vertex3dv, const GLdouble*, v)
GLF_V3(Vertex3f, GLfloat, x, GLfloat, y, GLfloat, z)
GLF_V1(Vertex3fv, const GLfloat*, v)
GLF_V3(Vertex3i, GLint, x, GLint, y, GLint, z)
GLF_V1(Vertex3iv, const GLint*, v)
GLF_V3(Vertex3s, GLshort, x, GLshort, y, GLshort, z)
GLF_V1(Vertex3sv, const GLshort*, v)
GLF_V4(Vertex4d, GLdouble, x, GLdouble, y, GLdouble, z, GLdouble, w)
GLF_V1(Vertex4dv, const GLdouble*, v)
GLF_V4(Vertex4f, GLfloat, x, GLfloat, y, GLfloat, z, GLfloat, w)
GLF_V1(Vertex4fv, const GLfloat*, v)
GLF_V4(Vertex4i, GLint, x, GLint, y, GLint, z, GLint, w)
GLF_V1(Vertex4iv, const GLint*, v)
GLF_V4(Vertex4s, GLshort, x, GLshort, y, GLshort, z, GLshort, w)
GLF_V1(Vertex4sv, const GLshort*, v)
GLF_V4_X(VertexPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid*, pointer)
GLF_V4_X(Viewport, GLint, x, GLint, y, GLsizei, width, GLsizei, height)

#ifdef DID_DEFINE_X_MACROS
#undef DID_DEFINE_X_MACROS
#undef GLF_V1_X
#undef GLF_V2_X
#undef GLF_V3_X
#undef GLF_V4_X
#endif
